version: x-{build}
configuration: Release
image: Visual Studio 2017

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

before_build:
- cmd: dotnet restore
- ps: gitversion /l console /output buildserver /updateAssemblyInfo
- cmd: SET APPVEYOR_BUILD_VERSION = %GitVersion_MajorMinorPatch%

build:
  publish_nuget: true
  parallel: true
  verbosity: minimal

test:
  assemblies: '**\*.Tests.dll'

deploy: off
