version: x-{build}
configuration: Release
image: Visual Studio 2017

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

before_build:
- cmd: dotnet restore
- ps: gitversion /l console /output buildserver
- ps: appveyor UpdateBuild -Version "$env:GitVersion_SemVer-$env:GitVersion_BuildMetaData"

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(GitVersion_NuGetVersion)
  package_version: $(GitVersion_NuGetVersion)
  assembly_version: $(GitVersion_MajorMinorPatch)
  file_version: $(GitVersion_MajorMinorPatch)
  informational_version: $(GitVersion_InformationalVersion)

build:
  publish_nuget: true
  parallel: true
  verbosity: minimal

test:
  assemblies: '**\*.Tests.dll'

deploy: off
