version: {build}
image: Visual Studio 2017
configuration: Release

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

install:
  - choco install gitversion -pre -y
  - cmd: dotnet restore
  - ps: gitversion /l console /output buildserver

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(GitVersion_SemVer)
  assembly_version: $(GitVersion_MajorMinorPatch)
  informational_version: $(GitVersion_InformationalVersion)

build:
  publish_nuget: true
  parallel: true
  verbosity: minimal

test:
  assemblies: '**\*.Tests.dll'

deploy: off
