version: x-{build}
configuration: Release
image: Visual Studio 2017

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

before_build:
- cmd: dotnet restore
- ps: gitversion /l console /output buildserver /updateAssemblyInfo


build_script:
  - dotnet pack -c %CONFIGURATION% --no-build --no-restore -p:Version=%GitVersion_MajorMinorPatch% -p:AssemblyVersion=%GitVersion_MajorMinorPatch%

test:
  assemblies: '**\*.Tests.dll'

deploy: off
